Реализация логики друзей и лайков
ArchieBar/filmorate-educationProject pull request #6
Opened 2024-01-24 11:21 UTC by ArchieBar

В целом - разобрался, немного запутался с зависимостями. Пометки в непонятных местах оставил

2024-01-24 20:07 UTC, dgumich requested changes

2024-01-24 20:07 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .filter(id -> userStorage.findUserByID(otherUserId).getFriends().contains(id))
userStorage.findUserByID(otherUserId).getFriends() надо вынести в локальную переменную. В чем профит? Ну мы раз сходим в "бд" достанем пользователя и его друзей и все, больше запросов к "бд" не будет. А так для каждого айди будем стучаться в "бд" что не есть хорошо.

2024-01-24 20:07 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getReleaseDate().isBefore(EARLIEST_RELEASE_DATE)) {
Валидация - это бизнес логика и должна быть в сервисном слое.

2024-01-24 20:07 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        log.info("Вызов POST /films: " + film);
Логгирование должно быть логически распределено. Здесь мы говорим про POST запрос, что относится к контроллеру, но не стореджу=) Надо перенести логгирование в правильный класс/метод.

2024-01-24 20:07 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        log.info("Вызов PUT /films: " + film);
Аналогично логирование надо вынести в контроллер, а валидацию в сервисный слой.

2024-01-24 20:07 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    private void validateUserName(User user) {
Валидирование должно быть в сервисном слое.

2024-01-25 13:08 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Исправил

2024-01-25 13:08 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        this.filmService = new FilmService(filmStorage);
Исправил

2024-01-25 13:09 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.getAllFilm();
Исправил

2024-01-25 13:09 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.createFilm(film);
Исправил

2024-01-25 13:10 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserStorage userStorage;
Исправил

2024-01-25 13:10 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        this.userService = new UserService(userStorage);
Исправил

2024-01-25 13:10 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userStorage.findUserByID(userId);
Исправил

2024-01-25 13:10 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userStorage.getAllUser();
Исправил

2024-01-25 13:12 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Service
Если правильно понял, то "заинжектить" объект можно через аннотацию @Autowired, грубо говоря, спринг сам понимает, какие объекты нам нужны для создания и создаёт, включая зависимые

2024-01-25 13:31 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    // Наверное, стоит добавить проверку на существование пользователя
Исправил, но пришлось добавить UserStorage в FilmService, вроде норм

2024-01-25 13:31 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getReleaseDate().isBefore(EARLIEST_RELEASE_DATE)) {
Исправил

2024-01-25 15:02 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        log.info("Вызов POST /films: " + film);
Исправил
Я правильно понимаю, что логировать лучше только тебе методы и запросы, которые как либо изменяют объекты? А к примеру методы по получению списков логировать не нужно

2024-01-25 15:02 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        log.info("Вызов PUT /films: " + film);
Исправил

2024-01-25 15:02 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    private void validateUserName(User user) {
Исправил

2024-01-25 20:53 UTC, dgumich approved these changes

2024-01-25 20:53 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +@Service
И да и нет=) Если в кратце: указать спрингу, что нужно создать объект, а так же настроить его можно 3 способами: 1) самый первый и старый через xml файл, будете потом проходить. До сих пор есть проекты где так создают 2) С помощью аннотации @Component и ее производных (@Controller/@Service/@RestController  и тд имеют внутри себя аннотацию компонент) 3) С помощью конфигурационного класса и аннотации @Bean (тоже будете потом проходить).
В реальности можно встретить все три подхода. Бывают случаи, когда подойдет только через конфигурационный файл. Об этом есть в спринг потрошителе, который советовал тебе посмотреть=)
Теперь о том как спринг понимает куда внедрять:
1) Как ты верно отметил, аннотация @Autowired говорит спрингу, что надо внедрить сюда объект, который у него есть 2) Спринг очень умный и сам внедряет в конструкторы (если он один), так работала 9 работа. Там не было аннотаций @Autowired, но был ломбок с его @ReqAllArgConstructor, который как раз создавал его. 3) Есть джавовская аннотация @Inject, которая тоже из коробки обрабатывается спрингом и наконец последний случай - 4) можно написать свою аннотацию и научить спринг ее обрабатывать. 
Как то так=)

2024-01-25 20:53 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    // Лучше ли сделать собственную аннотацию?
Тут простая логика, так что нет смысла в собственной аннотации.
Тем более аннотации добавляют "магию" и не всегда удобны в работе.
Обычно валидируют в коде, что бы можно было легко подебажить и проследить работу

2024-01-25 20:53 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    // Наверное, стоит добавить проверку на существование пользователя
Это нормально, сервисы часто работают не только с одной сущностью и есть потребность ходить в "бд" за ними. Так что другие стореджи (репозитории) - это ок. Так же как и сервис в сервисе - это тоже ок

2024-01-25 20:53 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        log.info("Вызов POST /films: " + film);
Такое ТЗ было в 9 работе (методы, которые изменяют объекты)=) В реальности логгируют на усмотрение и так же по тз. Так что это уже надо смотреть проект.

2024-02-06 18:06 UTC, merged