Финал
ArchieBar/filmorate-educationProject pull request #7
Opened 2024-02-26 21:40 UTC by ArchieBar

2024-02-27 21:25 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +@Qualifier("Film_DAO")
Данная аннотация ставится там где ты хочешь внедрить этот бин, а не над классом бина=) Вот, можешь почитать https://www.baeldung.com/spring-qualifier-annotation

2024-02-27 21:37 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::findUserById)
Аналогично, надо переделать на 1 запрос

2024-02-27 21:37 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = userStorage.findUserById(userId);
Так же надо добавить проверку, что пользователь не null

2024-02-27 21:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Integer> userFriends = userStorage.findUserById(userId).getFriends();
А если пользователь null? Будет NPE. Аналогично и на строке 123

2024-02-27 21:41 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::findUserById)
Теперь получение общих друзей можно записать одним запросом к бд. Надо исправить

2024-02-29 14:57 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService; // @Primary FilmDbStorage
Исправил

2024-02-29 14:57 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserService userService; // @Primary UserDbStorage
Исправил

2024-02-29 14:58 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +@Component("Film_DAO")
Мне показалось, так было бы удобнее

2024-02-29 14:58 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +@Qualifier("Film_DAO")
Исправил

2024-02-29 14:58 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +@Component("User_DAO")
Исправил

2024-02-29 14:59 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/model/film/Mpa.java
> +public class Mpa implements Serializable {
Испрвил

2024-02-29 15:00 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final FilmStorage filmStorage; // @Primary in FilmDbStorage (Film_DAO)
Исправил

2024-02-29 16:52 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = userStorage.findUserById(userId);
исправил

2024-02-29 16:52 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::findUserById)
исправил

2024-02-29 16:52 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Integer> userFriends = userStorage.findUserById(userId).getFriends();
исправил

2024-02-29 16:52 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::findUserById)
исправил

2024-02-29 16:52 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(userStorage::findUserById)
исправил

2024-02-29 19:10 UTC, dgumich requested changes

2024-02-29 19:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>          return new ErrorResponse("Не найдено", e.getMessage());
При обработке исключений(что здесь и происходит по сути) обычно эти исключения логируют. А то ответ пользователю отправим, а в логах про это ничего не будет. Поэтому добавь логирование во все хендлеры

2024-02-29 19:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService; // @Primary FilmDbStorage
Не исправил, до сих пор есть этот комментарий. Зачем он?=)
![image](https://github.com/ArchieBar/filmorate-educationProject/assets/42573998/71d34826-d243-4abb-aabf-0a23575d59db)

2024-02-29 19:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final UserService userService; // @Primary UserDbStorage
Аналогично, не исправил
![image](https://github.com/ArchieBar/filmorate-educationProject/assets/42573998/7b16afcf-68d0-48d4-8a50-7ea841797d20)

2024-02-29 19:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getFriends().contains(idFriend)) {
Тут можно NPE получить, так как не проверил, что пользователь не равен null

2024-02-29 19:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        user.removeFriend(friend);
Аналогично, NPE, потому что пользователь может быть null

2024-02-29 19:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          Film film = filmStorage.findFilmById(filmId);
NPE, фильм может быть null=)

2024-02-29 19:10 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          Film film = filmStorage.findFilmById(filmId);
Возможный NPE=)

2024-02-29 19:48 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
>          return new ErrorResponse("Не найдено", e.getMessage());
исправил

2024-02-29 19:50 UTC, ArchieBar commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (user.getFriends().contains(idFriend)) {
Я поменял вызов с userStorage на вызов с сервиса, там стоит проверка, так что NPE обработает 
![изображение](https://github.com/ArchieBar/filmorate-educationProject/assets/142429962/f322830b-9532-4d34-9207-6c95825f312c)

2024-02-29 20:17 UTC, merged